export const qrCodeObj = {
  usa: "/QR/USA.png",
  india: "/QR/India.png",
  abs: "/QR/ABS.png",
  bangladesh: "/QR/Bangladesh.png",
  china: "/QR/China.png",
  europe: "/QR/Europe.png",
  hdpe: "/QR/HDPE.png",
  iran: "/QR/Iran.png",
  ksa: "/QR/KSA.png",
  ldpe: "/QR/LDPE.png",
  lldpe: "/QR/LLDPE.png",
  nepal: "/QR/Nepal.png",
  pakistan: "/QR/Pakistan.png",
  pet: "/QR/PET.png",
  ps: "/QR/PS.png",
  pvc: "/QR/PVC.png",
  sriLanka: "/QR/Sri Lanka.png",
  turkey: "/QR/Turkey.png",
};
